### PR TITLE
Use ogg if mp3 is not supported

### PR DESCRIPTION
**Pull request by cqx931**

### CODE REVIEW

**Comment by dhowe** [comment]
Now it is downloading the mp3s instead of playing them... can you not recreate this on your chromium (not Google chrome) ? 

image

**Comment by cqx931** [comment]
no... everything works well with me, on all my browsers. So what I did was trying to support playing ogg files when mp3 is not supported.
This is pretty strange...

**Comment by cqx931** [comment]
Please give this a try: https://github.com/dhowe/Website/pull/91

**Comment by dhowe** [comment]
Good!

**Pull request merged**
