### PR TITLE
Add Bertha

### PR DESCRIPTION
**Pull request by cqx931**

### CODE REVIEW

**Comment by dhowe** [comment]
Good start... what I notice:
-- bertha large image should be centered
-- remove excess space around adset
-- click for hi-res doesn't work for bertha
-- needs text (daniel)

Also, can you ping Bertha and ask how if she is ok with her name being used?

**Comment by cqx931** [comment]
I have asked Bertha and she is ok with her name being used.

**Comment by dhowe** [comment]
nothing new to merge here, correct?

**Comment by cqx931** [comment]
Please check it again

**Comment by cqx931** [comment]
@dhowe

**Pull request merged**
